### ISSUE TITLE
WPuQ

### ISSUE THREAD

**Issue by SteveHaben** [low-voltage-loadforecasting/low-voltage-loadforecasting.github.io#16]
https://zenodo.org/record/5642902#.YgvowN_P1aR

"Electric load of 38 households measured in a small village in Lower Saxony, Germany. Data is available for voltage, reactive power and active power. Separate measurements are available for each total household load, for each heat pump and at the local power transformer. Different temporal and spatial aggregations are available for convenience."

Paper: https://www.nature.com/articles/s41597-022-01156-1

from paper:
"We provide data per household of apparent, active and reactive power (W), voltage (V), current (A) and the power factor (no unit) in 10 seconds to 60 minutes temporal resolution from May 2018 to the end of 2020"

Name:  research project Wind-Solar-Heat Pump District (WPuQ) 
Url: https://zenodo.org/record/5642902#.YgvowN_P1aR
Type: Residential and heat pump, and local power transformer
Customers: 38 households
Resolution: 10 seconds to 60minutes
Duration:  over 2 years (maybe 2 years 8 months)
Intervention: If an intervention like Time-of-Use or dynamic prices was part of the measurement campaign
Submetering: Yes
Weather: Yes
Location: Germany, Lower Saxony
Other:Power, voltage, current and power factor
Licence: [Creative Commons Attribution 4.0 International](https://creativecommons.org/licenses/by/4.0/legalcode)

**Comment by marcus-voss** [comment]
Added
