### ISSUE TITLE
Living Lab Catapult

### ISSUE THREAD

**Issue by SteveHaben** [low-voltage-loadforecasting/low-voltage-loadforecasting.github.io#17]
Name: Living Lab Catapult
Url:  https://usmart.io/org/esc/discovery?tags=Living%20Lab&order=_score&keywords=Living%20Lab&limit=20&offset=0
Type: Residential
Customers: ~100
Resolution: 15 min
Duration: few months, Winter 2018/19, 2019/20
Intervention: Heating plans
Submetering: Yes - heat pumps in some houses.
Weather: Yes
Location: UK
Other: gas usage, room temperature and humidity
Licence: https://usmart-static.s3-eu-west-1.amazonaws.com/Data+Sharing+Licence+08102019+v3.0.pdf

**Comment by marcus-voss** [comment]
Added
