### ISSUE TITLE
Newcastle/NPg primary substation demand data

### ISSUE THREAD

**Issue by deakinmt** [low-voltage-loadforecasting/low-voltage-loadforecasting.github.io#24]
Hi team, 

I recently published some demand data from primary substations in UK - not strictly low voltage using normal distribution system definitions, but colleagues Jethro Browell & Stephen Haben had suggested members on this group might find it interesting. 

Is on a cc-by 4.0 licence and is derived from the Northern Powergrid open data portal which has quite a permissive licence.

Dataset: "Annual Half-Hourly Real and Reactive Power Flows for 171 Primary Electrical Distribution Circuits in the North of England"

DOI: https://doi.org/10.25405/data.ncl.22047758

Let me know if you need any further info to add this here,

Best,
Matt

**Comment by SteveHaben** [comment]
Thanks @deakinmt Matt, I've added all the details we add to the table. Please check, two areas it would be useful to know is
1. Was there any interventions on the data?
2. Any other data shared with it?
Thanks again, great dataset.  


Name: NPGrid Primaries
Url: https://doi.org/10.25405/data.ncl.22047758
Type: Substation
Customers: 171
Resolution: 30 min
Duration: 1 year
Intervention: None
Submetering: No
Weather: No
Location: North East and Yorkshire and the Humber Region of England
Other: 
Licence: cc-by 4.0

**Comment by deakinmt** [comment]
Thanks @SteveHaben, for (1), I suppose by interventions do you mean processing etc? In which case yes, there were three steps: (i) firstly, real and reactive powers were pulled out (which in some cases removed duplicate entries); then, (ii) these are combined to create apparent powers as reported. For the 'cleaned' version, I created the weekend/weekday average profiles, then used these to fill in missing values (this is a little crude, I am sure there are better methods, but was sufficient for what I am using this for).

For (2), at the moment those are the only data I needed from the NPg data portal and so I would answer no. But there is quite a lot of other stuff on that data portal (e.g., voltages) that at some point I might be going through.

Also, I guess what you have listed is a standard pro-forma, but fyi, it is 171 primary 'circuits' rather than customers (each time series might typically represent demand from 100s - 1000s of customers).

**Comment by marcus-voss** [comment]
I have pushed the data now!

**Comment by marcus-voss** [comment]
Added with: https://github.com/low-voltage-loadforecasting/low-voltage-loadforecasting.github.io/commit/d9b154c15ae2c18bd040ef1ec49d4247dff69dfa
