### ISSUE TITLE
Moroccan Buildings’ Electricity Consumption Dataset (MORED)

### ISSUE THREAD

**Issue by MOREDataset** [low-voltage-loadforecasting/low-voltage-loadforecasting.github.io#26]
- **Name:** Moroccan Buildings’ Electricity Consumption Dataset (MORED)
- **Url:** https://moredataset.github.io/MORED/
- **Type:** Residential", "Industrial"
- **Customers:** Number of households: 12+
- **Resolution:** 5 or 10 seconds.
- **Duration:** From 1 to 3 months.
- **Intervention:** No.
- **Submetering:** Yes.
- **Weather:** No.
- **Location:** Three cities from Morocco (Tetuán, Rabat, & Sale).
- **Other:** No.
- **Licence:** Licence: Free (Attribution, E-Mail)
```
@article{ahajjam2020mored,
title={MORED: a Moroccan buildings’ electricity consumption dataset},
author={Ahajjam, Mohamed Aymane and Bonilla Licea, Daniel and Essayeh, Chaimaa and Ghogho, Mounir and Kobbane, Abdellatif},
journal={Energies},
volume={13},
number={24},
pages={6737},
year={2020},
publisher={MDPI}}

**Comment by marcus-voss** [comment]
pushed and publised!
