### ISSUE TITLE
OPSCI - Open SCI

### ISSUE THREAD

**Issue by SteveHaben** [low-voltage-loadforecasting/low-voltage-loadforecasting.github.io#30]
Name: OPSCI - Open SCI
Url: https://www.elektro-ljubljana.si/projekti/ArtMID/1374/ArticleID/2156/OPSCI-Open-SCI
Type: Substation
Customers: One
Resolution: 15minutes
Duration: 4 years
Intervention: None
Submetering: Yes
Weather: No
Location: Country and possibly city or Region
Other: Voltage
Licence:

**Comment by marcus-voss** [comment]
Added
